### ISSUE TITLE
App refuse to save with error "not found"

### ISSUE THREAD

**Issue by Reinachan** [youpie/Iconic#12]
Whenever I try to save a folder, whether I'm using an svg or png for the icon, it gets stuck when attempting to save. It seems to panic at an unhandled unwrap due to not finding a folder or directory. Don't know if that's referring to the icon or the folder it wants to save it to.

I'm running this through the flatpak and I've tried giving the flatpak filesystem permissions but that didn't work either.

```
❯ flatpak run nl.emphisia.icon

(folder_icon:2): Gtk-WARNING **: 01:21:46.606: Unknown key gtk-modules in /home/nina/.var/app/nl.emphisia.icon/config/gtk-4.0/settings.ini

(folder_icon:2): Adwaita-WARNING **: 01:21:46.628: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
File found in cache at: "/home/nina/.var/app/nl.emphisia.icon/cache/folder.svg"
"/home/nina/Pictures/icons/applications-games-symbolic.svg"
thread 'main' panicked at src/objects/file.rs:32:61:
called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried doing a backtrace, though it didn't add anything that seemed of value other than referring to `g_main_context_iteration`, `g_application_run`, and `__libc_start_main`. Those don't sound very useful to me though, but mentioning them just in case.

**Comment by Reinachan** [comment]
I did some investigation and figured where it failed in the code. It fails when saving the file. It goes to the else condition on line 28 because the default save format is .png instead of .svg and it crashes on the unwrap in there. So I thought I'd try saving it as an .svg instead. And while this stopped the app from crashing, it didn't actually end up saving the file. I guess that's because you're not supposed to save them as .svg though xD

**Comment by youpie** [comment]
ohw yeah, I do not support saving as an svg. I think I have already fixed this issue in the dev version, I'll release that version asap.currently, if you are trying to save am image with a space in the name I think it fails

**Comment by Reinachan** [comment]
I'll try again once the update is out, though I'd like to point out that I didn't have any spaces in the path or the filename of either the folder icon I was trying to make or the icon I was using in it. Additionally, I only tested saving as .svg for the sake of seeing what happened after I checked the source code. I've also tried both a .svg for the icon and a .png just to check, though neither worked

**Comment by youpie** [comment]
could you share both the top icon you were trying to use. and the name you were trying to save it as?

**Comment by Reinachan** [comment]
Sure!

I was using this icon which I got from the app "Icon Library". 
![applications-games-symbolic](https://github.com/user-attachments/assets/768e8ae7-6407-4e9a-9b8a-9ad6ff0c84a0)

Then I tried to save it to this path:
`/home/nina/Pictures/folder_icons/games_folder.png`

This resulted in the error I shared above with path not found.

**Comment by youpie** [comment]
okay i have tested it. I get the same issue, but the new version fixes it!

**Comment by Reinachan** [comment]
Yeah, the new version fixes it for me too. Thanks for pushing out a fix. Closing this issue :)
