### ISSUE TITLE
Change folder color with right-click

### ISSUE THREAD

**Issue by vanillajonathan** [youpie/Iconic#27]
I wanted to change folder icon but didn't know how to, eventually I found it in the Preferences dialog.

It would be good if it I could right-click (or double click) on the folder in the main screen (on the `GtkPicture` widget with the name `image_view`) as this would make it more discoverable and also quicker.

**Comment by youpie** [comment]
good idea, but i dont know how to implement it 😅

**Comment by vanillajonathan** [comment]
I think that on your [`Gtk.Picture`](https://docs.gtk.org/gtk4/class.Picture.html) you can call the [`add_controller`](https://docs.gtk.org/gtk4/method.Widget.add_controller.html) method (inherited from `Gtk.Widget`) to add a [`Gtk.GestureClick`](https://docs.gtk.org/gtk4/class.GestureClick.html) which connects [GDK.BUTTON_SECONDARY](https://docs.gtk.org/gdk4/const.BUTTON_SECONDARY.html) to bring up a menu.

**Comment by youpie** [comment]
It is now added in iconic
