### ISSUE TITLE
[Feature Request] Change "saved file" toast to "File Saved" and add a "Open File Location" button in the toast, next to the text

### ISSUE THREAD

**Issue by amethystgosling** [youpie/Iconic#4]
The button when pressed, opens the file in Nautilus and selects it.
This is useful if one wants to do something with the file using another program. For example, further manipulations in some other image manipulation program or renaming the file, maybe even deleting or copying it.

**Comment by youpie** [comment]
This seems like a good idea, will try to add this soon!

**Comment by youpie** [comment]
I have added the feature!
