### ISSUE TITLE
Preset icons

### ISSUE THREAD

**Issue by candroid-man** [youpie/Iconic#5]
I've been looking for an app like this for one weirdly specific reason: I like having my games folder in my home folder, and I want an icon that fits in with the folders with icons (documents, photos, music, etc.) for my games folder. It would be cool if you could have some icons pre-installed with the app so people can quickly common icons that aren't available by default in GNOME.

It would be cool to have a games icon, and also an appimage icon. If I find any good files I'll share them here

**Comment by youpie** [comment]
good idea, i want to implement this. for now i just use [this app](https://flathub.org/apps/org.gnome.design.IconLibrary), save the files and load it into iconic

**Comment by youpie** [comment]
In the newest version which I'll release soon, you can drag and drop images from [icon library](https://flathub.org/apps/org.gnome.design.IconLibrary) directly into iconic. This will make it much easier to create icons

**Comment by smezzy** [comment]
presets for folder colors would also be cool!

**Comment by frandavid100** [comment]
Subscribing to this issue, since I always use Iconic and Icon library in tandem. It would be awesome to only use Iconic instead.

**Comment by youpie** [comment]
I find using icon library works more than good enough
