### ISSUE TITLE
Blue square instead of logo when using monochrome

### ISSUE THREAD

**Issue by candroid-man** [youpie/Iconic#6]
![image](https://github.com/user-attachments/assets/1650106b-a47c-4ef9-9429-6dbcf3d10e8a)

Here are some of the files I have tried to use in Iconic:

![proton-drive-logo-9763A975ED-seeklogo com](https://github.com/user-attachments/assets/7cb664ec-4717-439b-ae95-884af78c8593)
![proton-drive](https://github.com/user-attachments/assets/439ff82a-e06c-4ba8-9974-318af8385ae3)
![communityIcon_qggv2tch6m191](https://github.com/user-attachments/assets/d6751748-146f-4aa7-89c7-f261e28b691b)

**Comment by youpie** [comment]
try sliding the threshold slider

**Comment by candroid-man** [comment]
I tried adjusting every slider per image

**Comment by youpie** [comment]
![afbeelding](https://github.com/user-attachments/assets/c350e022-f265-45f6-931a-e9204ce9e218)
Hmm I did manage it for the colored image, but not for the outline one. I will see why that is

**Comment by youpie** [comment]
@candroid-man I found the issue why the black and white image did not get properly converted to monochrome. That is now fixed! Once I release a new version it should work for you

**Comment by candroid-man** [comment]
Thanks man!
