### ISSUE TITLE
Feature Request: Support drag & drop from Nautilus

### ISSUE THREAD

**Issue by amethystgosling** [youpie/Iconic#9]
... and when open drags & drops from Nautilus. the application asks to know if it is the top icon or the folder icon. This is especially useful since one might not want to pick the icons from the GTK file picker since right now it is kind of crappy.

**Comment by youpie** [comment]
This is indeed a feature I really want to implement. I'll put it next up when I have the motivation!

**Comment by youpie** [comment]
i did it!

**Comment by amethystgosling** [comment]
> i did it!

When will you push it in a new version?

**Comment by youpie** [comment]
@amethystgosling when i think its ready. 1 month, maybe more, maybe less
